{% set name = "ocl-icd" %}
{% set version = "2.3.2" %}
{% set sha256 = "ec47d7dcd961ea06695b067e8b7edb82e420ddce03e0081a908c62fd0b8535c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OCL-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #git_url: https://github.com/OCL-dev/{{ name }}.git
  #git_rev: 97e3fb5d4b005f931f224d9f7903f95ed66ec642

  patches:
  # Makes ocl-icd install the OpenCL headers it ships
    - install-headers.patch
  # Recursively check for icds in vendor dir
    - check_icds_recursively.diff

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage("ocl-icd") }}

requirements:
  build:
    - pkg-config
    - libtool
    - automake
    - autoconf
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ruby *
  host:

test:
  requires:
    - {{ compiler('c') }}
  source_files:
    - ocl_test.c
  commands:
    - test -f "${PREFIX}/include/CL/cl.h"
    - test -f "${PREFIX}/lib/libOpenCL.so.1"
    - test -d "${PREFIX}/etc/OpenCL/vendors"
    - $CC -o test ocl_test.c -L${PREFIX}/lib -lOpenCL -I${PREFIX}/include
    - ./test
    - ./test | grep "No platforms found!"

about:
  home: https://github.com/OCL-dev/ocl-icd
  # https://forge.imag.fr/projects/ocl-icd/ also exists but appears out of date
  license: BSD-2-Clause
  license_file: COPYING
  summary: An OpenCL ICD Loader under an open-source license

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - matthiasdiener
