{% set name = "ocl-icd" %}
{% set version = "2.2.12" %}
{% set sha256 = "17500e5788304eef5b52dbe784cec197bdae64e05eecf38317840d2d05484272" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OCL-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
  # Makes ocl-icd install the OpenCL headers it ships
  - install-headers.patch

build:
  number: 1002
  skip: True  # [not linux]

requirements:
  build:
    - pkg-config
    - libtool
    - automake
    - autoconf
    - {{ compiler('c') }}
  host:

test:
  commands:
    - test -f "${PREFIX}/include/CL/cl.h"     # [unix]
    - test -f "${PREFIX}/lib/libOpenCL.so.1"  # [linux]
    - test -d "${PREFIX}/etc/OpenCL/vendors"

about:
  home: https://github.com/OCL-dev/ocl-icd
  # https://forge.imag.fr/projects/ocl-icd/ also exists but appears out of date
  license: BSD
  license_file: COPYING
  summary: 'An OpenCL ICD Loader under an open-source license'

extra:
  recipe-maintainers:
    - inducer
