appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mJxZ8Y0WjPBV9anm78NtzZ3EawuTSNfXfe/6/cPnGj79VwnpBr8uF1cwXt/PV+zQyLrqIg78tANwjWim3W/IyZfsTojliu1zrVudcOLTyUwWC/T667dIEn7V6/AVmdCDHbyteS+pbcdX4iCean3nfLwsTmQ0zwmNcYM387ffav/apgO2aL7HahureJO7qf+vPPQlfPQvZALN+PoP6UpWfOBNpcWWal04P2oSdj74aTpBtMgfSIJszTFTX2UH/VD/Zbzy1+gjxdET6fmtxpcBCdAD17jjtD8h6ZBiMjYjpeYkgBSp+O/OVkyzdroyPvZ9XOeI2JJNjOkfxwsGwBGKgSQ+Ru8nJMgwm+1YXcTqmo1YRfvDjUwu48Fz7Zq1NMVLTthI9kMRkg89IGxBtBWYfsFHPsCn80HV7YomVKJynEGdz6nKJE5Rk0LyV/rJUaBCskZYgize4HEntM60PmQte9o1Xpe6BSY1F0g5Epu4VNrSCVzR27C3y8LMpo3qouWgErOUHoQiYAfVLes8Zu4UJuoxJNr3A8wrfv2pMEfWsMlGSLWI/Y8bj7w1sj/JrjiVl2DOYURdut3D1EmeX2V8lB1vEvTUylri9y2V2noKCUFeV8J+SMDLzNYBSC4bK3YwJUpcYXIi2ftnPlx/s1D5PjuIYkZEU1rp9xW+HUrM1T8=}
